---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: fleet-tenant-sync
spec:
  interval: 5m0s
  path: ./tenants/kla/placeholder
  prune: true
  serviceAccountName: flux-reconciler
  sourceRef:
    kind: GitRepository
    name: tenant-repo
  validation: client
  targetNamespace: placeholder
  dependsOn:
    - name: fleet-tenant-commons-sync