---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: app-repo
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: app-repo-auth
  url: ssh://git@github.com/rkdutta/app-repo
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tenant-repo
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: tenant-repo-auth
  url: ssh://git@github.com/rkdutta/tenant-repo