apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/

namespace: acc
patchesStrategicMerge:
  - |-
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
    kind: Kustomization
    metadata:
      name: fleet-tenant-sync
    spec:
      path: ./tenants/kla/acc
      targetNamespace: acc
  - |-
    apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
    kind: Kustomization
    metadata:
      name: fleet-tenant-commons-sync
    spec:
      targetNamespace: acc